### ISSUE TITLE
Request to learn from this repository

### ISSUE THREAD

**Issue by Gifted-s** [fjall-rs/lsm-tree#54]
Hi Mavin, I am the creator [https://github.com/Gifted-s/velarixdb](https://github.com/Gifted-s/velarixdb).

It's an LSM also but it focuses on reducing IO amplification with this paper from the University of Wisconsin Maddison (https://www.usenix.org/system/files/conference/fast16/fast16-papers-lu.pdf)

I want the storage engine to be entirely different from the existing ones, especially regarding async IO.

But since this is the only standard LSM storage I can find for now and I am pretty new to writing storage engines. I am learning so much from it.  I tried reimplementing most of the features to have a deep understanding but that might look like copying the code without permission so I would like to clarify that it's all for learning purposes and I do not aim to use this code.

The original codebase for VelarixDB is async IO, and it differs from other implementations. I have completely wiped out the branch that featured code from this repository in VelarixDB and all the code is now independent of any code from this repository, I would like you to check and confirm this. https://github.com/Gifted-s/velarixdb

Thanks.

**Comment by Gifted-s** [comment]
I would also like to connect with you via email or any medium. VelarixDB is still young and there is a long way to. I need experts I can ask questions from and I believe you @marvin-j97, can help

**Comment by marvin-j97** [comment]
The code is licensed as MIT OR Apache 2,

MIT saying:

> Permission is hereby granted, free of charge, to [...] use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software [...] (with the following condition) [...] The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software

Meaning that derivative work contains the [license](https://github.com/fjall-rs/lsm-tree/blob/main/LICENSE-MIT), not necessarily because I want the credit, but it also helps with signalling what code is derivative, so it is in the best interest of the derivative work.

> I would also like to connect with you via email or any medium

I don't hand out my email address, but there is a Discord server linked in the README file.
